import type {
  DriftReport,
  DriftedFile,
  OutputFormat,
  RiskLevel,
} from "./types.js";

export interface ReporterOptions {
  format: OutputFormat;
  verbose?: boolean;
}

export function render(report: DriftReport, options: ReporterOptions): string {
  switch (options.format) {
    case "json":
      return renderJson(report);
    case "markdown":
      return renderMarkdown(report);
    default:
      return renderTable(report, options.verbose ?? false);
  }
}

const COL = { file: 48, pr: 10, main: 12, overlap: 9, risk: 6 };
const DIVIDER_WIDTH = COL.file + COL.pr + COL.main + COL.overlap + COL.risk + 4;

function renderTable(report: DriftReport, verbose: boolean): string {
  const { prInfo: pr, driftedFiles, cleanFiles, prFiles } = report;
  const lines: string[] = [];

  lines.push(`PR #${pr.number}: ${pr.title}`);
  lines.push(`Branch: ${pr.headBranch} → ${pr.baseBranch}`);
  lines.push("");

  if (driftedFiles.length === 0) {
    lines.push("✅  No drift detected. This PR is clean.");
    lines.push(`    ${prFiles.length} file(s) checked, 0 conflicts found.`);
    return lines.join("\n");
  }

  const pct = ((driftedFiles.length / prFiles.length) * 100).toFixed(0);
  lines.push(
    `⚠️  Drift detected in ${driftedFiles.length} of ${prFiles.length} file(s) (${pct}%)\n`,
  );

  // Header row
  lines.push(
    pad("FILE", COL.file) +
      " " +
      padLeft("PR LINES", COL.pr) +
      " " +
      padLeft("MAIN LINES", COL.main) +
      " " +
      padLeft("OVERLAP", COL.overlap) +
      " " +
      "RISK",
  );
  lines.push("─".repeat(DIVIDER_WIDTH));

  for (const f of driftedFiles) {
    const fname = truncate(f.filename, COL.file);
    const row =
      pad(fname, COL.file) +
      " " +
      padLeft(String(f.prChanges), COL.pr) +
      " " +
      padLeft(String(f.mainChanges), COL.main) +
      " " +
      padLeft(formatPct(f.overlapScore), COL.overlap) +
      " " +
      `${riskEmoji(f.risk)} ${f.risk}`;
    lines.push(row);

    if (verbose && f.overlapLines.length > 0) {
      lines.push(
        `    ↳ overlapping lines: ${formatLineRanges(f.overlapLines)}`,
      );
    }

    if (f.aiInsight) {
      lines.push(`    💡 ${f.aiInsight}`);
    }
  }

  lines.push("");
  lines.push(summaryAdvice(report.driftedFiles));
  return lines.join("\n");
}

function renderMarkdown(report: DriftReport): string {
  const { prInfo: pr, driftedFiles, prFiles } = report;
  const lines: string[] = [];

  lines.push("<!-- prcheck -->");
  lines.push("## 🔍 prcheck drift report\n");

  if (driftedFiles.length === 0) {
    lines.push(
      `✅ **No drift detected.** All ${prFiles.length} file(s) checked are clean relative to \`${pr.baseBranch}\`.`,
    );
    return lines.join("\n");
  }

  lines.push(
    `**${driftedFiles.length} of ${prFiles.length} files** in this PR have also been modified on ` +
      `\`${pr.baseBranch}\` since this branch diverged. Review these carefully before merging.\n`,
  );

  const hasAiInsights = driftedFiles.some((f) => f.aiInsight);
  const headerRow = hasAiInsights
    ? "| File | PR lines | Main lines | Overlap | Risk | AI insight |"
    : "| File | PR lines | Main lines | Overlap | Risk |";
  const separatorRow = hasAiInsights
    ? "|------|----------|------------|---------|------|------------|"
    : "|------|----------|------------|---------|------|";

  lines.push(headerRow);
  lines.push(separatorRow);

  for (const f of driftedFiles) {
    const aiCol = hasAiInsights ? ` ${f.aiInsight ?? "—"} |` : "";
    lines.push(
      `| \`${f.filename}\` | ${f.prChanges} | ${f.mainChanges} | ` +
        `${formatPct(f.overlapScore)} | ${riskEmoji(f.risk)} ${f.risk} |${aiCol}`,
    );
  }

  lines.push("");
  lines.push(`> ${summaryAdvice(driftedFiles)}`);
  lines.push("");
  lines.push(
    "<sub>Generated by [prcheck](https://github.com/your-username/prcheck) — " +
      "semantic drift detection for pull requests.</sub>",
  );

  return lines.join("\n");
}

function renderJson(report: DriftReport): string {
  const { prInfo: pr, driftedFiles, cleanFiles, prFiles } = report;

  const highestRisk =
    driftedFiles.length === 0 ? "none" : (driftedFiles[0].risk as string); // already sorted by risk

  const payload = {
    pr: {
      number: pr.number,
      title: pr.title,
      headBranch: pr.headBranch,
      baseBranch: pr.baseBranch,
    },
    summary: {
      totalFiles: prFiles.length,
      driftedFiles: driftedFiles.length,
      driftPercentage: parseFloat(
        ((driftedFiles.length / prFiles.length) * 100).toFixed(1),
      ),
      highestRisk,
    },
    drifted: driftedFiles.map((f) => ({
      filename: f.filename,
      prLinesChanged: f.prChanges,
      mainLinesChanged: f.mainChanges,
      overlapScore: parseFloat(f.overlapScore.toFixed(3)),
      overlapLines: f.overlapLines,
      risk: f.risk,
      ...(f.aiInsight ? { aiInsight: f.aiInsight } : {}),
    })),
    clean: cleanFiles,
  };

  return JSON.stringify(payload, null, 2);
}

export function riskEmoji(risk: RiskLevel): string {
  return { high: "🔴", medium: "🟡", low: "🟢" }[risk];
}

export function summaryAdvice(driftedFiles: DriftedFile[]): string {
  if (driftedFiles.length === 0) return "No drift detected.";

  const highest = driftedFiles[0].risk; // sorted, so first = worst
  if (highest === "high") {
    return (
      "High-risk drift found. Re-read the drifted files on main before requesting review. " +
      "Consider rebasing to resolve conflicts early."
    );
  }
  if (highest === "medium") {
    return (
      "Moderate drift detected. These files changed on both branches — " +
      "verify the logic is still consistent after merge."
    );
  }
  return "Low-risk drift. Files overlap slightly but changes appear minimal.";
}

export function formatLineRanges(lines: number[]): string {
  if (lines.length === 0) return "";

  const ranges: string[] = [];
  let start = lines[0];
  let end = lines[0];

  for (let i = 1; i < lines.length; i++) {
    if (lines[i] === end + 1) {
      end = lines[i];
    } else {
      ranges.push(start === end ? `${start}` : `${start}-${end}`);
      start = end = lines[i];
    }
  }
  ranges.push(start === end ? `${start}` : `${start}-${end}`);

  return ranges.join(", ");
}

function pad(s: string, width: number): string {
  return s.padEnd(width);
}

function padLeft(s: string, width: number): string {
  return s.padStart(width);
}

function truncate(s: string, max: number): string {
  return s.length > max ? `…${s.slice(-(max - 1))}` : s;
}

function formatPct(score: number): string {
  return `${(score * 100).toFixed(0)}%`;
}
