import type { DriftReport, OutputFormat } from "./types.js";
import {
  COL,
  DIVIDER_WIDTH,
  riskEmoji,
  summaryAdvice,
  formatLineRanges,
  pad,
  padLeft,
  truncate,
  formatPct,
} from "./format.js";

export interface ReporterOptions {
  format: OutputFormat;
  verbose?: boolean;
}

export function render(report: DriftReport, options: ReporterOptions): string {
  switch (options.format) {
    case "json":
      return renderJson(report);
    case "markdown":
      return renderMarkdown(report);
    default:
      return renderTable(report, options.verbose ?? false);
  }
}

function renderTable(report: DriftReport, verbose: boolean): string {
  const { prInfo: pr, driftedFiles, prFiles } = report;
  const lines: string[] = [];

  lines.push(`PR #${pr.number}: ${pr.title}`);
  lines.push(`Branch: ${pr.headBranch} → ${pr.baseBranch}`);
  lines.push("");

  if (driftedFiles.length === 0) {
    lines.push("✅  No drift detected. This PR is clean.");
    lines.push(`    ${prFiles.length} file(s) checked, 0 conflicts found.`);
    return lines.join("\n");
  }

  const pct = ((driftedFiles.length / prFiles.length) * 100).toFixed(0);
  lines.push(
    `⚠️  Drift detected in ${driftedFiles.length} of ${prFiles.length} file(s) (${pct}%)\n`,
  );

  lines.push(
    pad("FILE", COL.file) +
      " " +
      padLeft("PR LINES", COL.pr) +
      " " +
      padLeft("MAIN LINES", COL.main) +
      " " +
      padLeft("OVERLAP", COL.overlap) +
      " " +
      "RISK",
  );
  lines.push("─".repeat(DIVIDER_WIDTH));

  for (const f of driftedFiles) {
    lines.push(
      pad(truncate(f.filename, COL.file), COL.file) +
        " " +
        padLeft(String(f.prChanges), COL.pr) +
        " " +
        padLeft(String(f.mainChanges), COL.main) +
        " " +
        padLeft(formatPct(f.overlapScore), COL.overlap) +
        " " +
        `${riskEmoji(f.risk)} ${f.risk}`,
    );

    if (verbose && f.overlapLines.length > 0) {
      lines.push(
        `    ↳ overlapping lines: ${formatLineRanges(f.overlapLines)}`,
      );
    }

    if (f.aiInsight) {
      lines.push(`    💡 ${f.aiInsight}`);
    }
  }

  lines.push("");
  lines.push(summaryAdvice(driftedFiles));
  return lines.join("\n");
}

const MD_HEADER = "| File | PR lines | Main lines | Overlap | Risk |";
const MD_SEPARATOR = "|------|----------|------------|---------|------|";
const MD_HEADER_AI =
  "| File | PR lines | Main lines | Overlap | Risk | AI insight |";
const MD_SEPARATOR_AI =
  "|------|----------|------------|---------|------|------------|";

function renderMarkdown(report: DriftReport): string {
  const { prInfo: pr, driftedFiles, prFiles } = report;
  const lines: string[] = [];

  lines.push("<!-- prcheck -->");
  lines.push("## 🔍 prcheck drift report\n");

  if (driftedFiles.length === 0) {
    lines.push(
      `✅ **No drift detected.** All ${prFiles.length} file(s) checked are clean relative to \`${pr.baseBranch}\`.`,
    );
    return lines.join("\n");
  }

  lines.push(
    `**${driftedFiles.length} of ${prFiles.length} files** in this PR have also been modified on ` +
      `\`${pr.baseBranch}\` since this branch diverged. Review these carefully before merging.\n`,
  );

  const hasAiInsights = driftedFiles.some((f) => f.aiInsight);
  lines.push(hasAiInsights ? MD_HEADER_AI : MD_HEADER);
  lines.push(hasAiInsights ? MD_SEPARATOR_AI : MD_SEPARATOR);

  for (const f of driftedFiles) {
    const aiCol = hasAiInsights ? ` ${f.aiInsight ?? "—"} |` : "";
    lines.push(
      `| \`${f.filename}\` | ${f.prChanges} | ${f.mainChanges} | ` +
        `${formatPct(f.overlapScore)} | ${riskEmoji(f.risk)} ${f.risk} |${aiCol}`,
    );
  }

  lines.push("");
  lines.push(`> ${summaryAdvice(driftedFiles)}`);
  lines.push("");
  lines.push(
    "<sub>Generated by [prcheck](https://github.com/your-username/prcheck) — " +
      "semantic drift detection for pull requests.</sub>",
  );

  return lines.join("\n");
}

function renderJson(report: DriftReport): string {
  const { prInfo: pr, driftedFiles, cleanFiles, prFiles } = report;

  const payload = {
    pr: {
      number: pr.number,
      title: pr.title,
      headBranch: pr.headBranch,
      baseBranch: pr.baseBranch,
    },
    summary: {
      totalFiles: prFiles.length,
      driftedFiles: driftedFiles.length,
      driftPercentage: parseFloat(
        ((driftedFiles.length / prFiles.length) * 100).toFixed(1),
      ),
      highestRisk: driftedFiles.length === 0 ? "none" : driftedFiles[0].risk,
    },
    drifted: driftedFiles.map((f) => ({
      filename: f.filename,
      prLinesChanged: f.prChanges,
      mainLinesChanged: f.mainChanges,
      overlapScore: parseFloat(f.overlapScore.toFixed(3)),
      overlapLines: f.overlapLines,
      risk: f.risk,
      ...(f.aiInsight ? { aiInsight: f.aiInsight } : {}),
    })),
    clean: cleanFiles,
  };

  return JSON.stringify(payload, null, 2);
}
